### ISSUE TITLE
Add papers section

### ISSUE THREAD

**Issue by raivivek** [AGV-IIT-KGP/awesome-computer-vision#1]
Here are a couple of links that might be helpful for a start:

http://www.cvpapers.com/
http://computervisionblog.wordpress.com/2012/02/10/the-most-cited-papers-in-computer-vision/
https://github.com/papers-we-love/papers-we-love

**Comment by raivivek** [comment]
@hargup

**Comment by hargup** [comment]
Sorry @vivekiitkgp for not responding. Thanks for your suggestion I'll incorporate it.

**Comment by raivivek** [comment]
Superseded by better collection at https://github.com/jbhuang0604/awesome-computer-vision
